Repository FilecoinFoundationWeb/filecoin-foundation, pull requests merged in 2024-11, with the labels that each got.

#778 Update Event “fil-bangkok-2024”
  public/assets/images/6824849a-d33b-4a0d-b701-713354dffd29.webp
  public/assets/images/anjali-george-headshot.webp
  public/assets/images/david-dao-headshot.webp
  public/assets/images/ethan-chae-headshot.webp
  public/assets/images/fleek-logo.webp
  public/assets/images/glif-logo.webp
  public/assets/images/leah-callon-butler-headshot.webp
  public/assets/images/long_white.png
  public/assets/images/mark-rydon-headshot.webp
  public/assets/images/masa-kikuchi-headshot.webp
  public/assets/images/megan-klimen-headshot.webp
  public/assets/images/rachel-green-horn-headshot.webp
  public/assets/images/sherry-chung-headshot.webp
  public/assets/images/ted-liao-headshot.webp
  public/assets/images/zetacube-logo.webp
  public/assets/images/zetacube_logo_white2.webp
  src/content/ecosystem-explorer/projects/glif.md
  src/content/events/fil-bangkok-2024.md
Labels: decap-cms/pending_publish

#781 Update Event “fil-bangkok-2024”
  src/content/events/fil-bangkok-2024.md
Labels: decap-cms/pending_publish

#782 Update Event “fil-bangkok-2024”
  public/assets/images/ayush-ranjan.webp
  public/assets/images/georgios-vlachos-headshot.webp
  public/assets/images/jaden-yan-headshot.webp
  public/assets/images/molly-mackinlay-headshot.webp
  public/assets/images/patrick-kearney-headshot.webp
  public/assets/images/protocol-labs-logo.png
  public/assets/images/roman-nebo-headshot.webp
  src/content/events/fil-bangkok-2024.md
Labels: decap-cms/pending_publish

#790 Update Event “fil-bangkok-2024”
  src/content/events/fil-bangkok-2024.md
Labels: decap-cms/pending_publish

#791 Update Event “fil-bangkok-2024”
  src/content/events/fil-bangkok-2024.md
Labels: decap-cms/pending_publish

#792 Update Event “fil-bangkok-2024”
  src/content/events/fil-bangkok-2024.md
Labels: decap-cms/pending_publish

#797 Update Event “fil-bangkok-2024”
  public/assets/images/ceramic-logo.webp
  src/content/events/fil-bangkok-2024.md
Labels: decap-cms/pending_publish

#796 Create Blog Post “an-inside-look-at-a-filecoin-data-center”
  public/assets/images/102224-dcent-documentary.webp
  src/content/blog/an-inside-look-at-a-filecoin-data-center.md
Labels: decap-cms/pending_publish

#795 Create Blog Post “announcing-the-filecoin-orbit-university-challenge”
  src/content/blog/announcing-the-filecoin-orbit-university-challenge.md
Labels: decap-cms/pending_publish

#800 Update Event “fil-bangkok-2024”
  src/content/events/fil-bangkok-2024.md
Labels: decap-cms/pending_publish

#803 Update Blog Post “announcing-the-filecoin-orbit-university-challenge”
  public/assets/images/orbit-university-challenge.webp
  src/content/blog/announcing-the-filecoin-orbit-university-challenge.md
Labels: decap-cms/draft

#807 Update Event “fil-bangkok-2024”
  public/assets/images/alejandro-rodri-guez-headshot.webp
  src/content/events/fil-bangkok-2024.md
Labels: decap-cms/pending_publish

#808 Update Event “fil-bangkok-2024”
  public/assets/images/hannahhoward-headshot.webp
  public/assets/images/konstantin-tkachuk.webp
  src/content/events/fil-bangkok-2024.md
Labels: decap-cms/pending_publish

#811 Update Event “fil-bangkok-2024”
  public/assets/images/jonathan-victor-headshot-.webp
  public/assets/images/sarah-thiam.webp
  src/content/events/fil-bangkok-2024.md
Labels: decap-cms/pending_publish

#810 Update Blog Post “announcing-the-filecoin-orbit-university-challenge”
  src/content/blog/announcing-the-filecoin-orbit-university-challenge.md
Labels: decap-cms/pending_review

#812 Update Event “fil-bangkok-2024”
  src/content/events/fil-bangkok-2024.md
Labels: decap-cms/pending_publish

#813 Update Event “fil-bangkok-2024”
  src/content/events/fil-bangkok-2024.md
Labels: decap-cms/pending_publish

#836 Create Blog Post “filecoin-as-the-infrastructure-for-decentralized-ai”
  public/assets/images/blog-post-header-fast-company-we-made-the-list.webp
  src/content/blog/filecoin-as-the-infrastructure-for-decentralized-ai.md
Labels: decap-cms/pending_publish

#840 Update Blog Post “filecoin-as-the-infrastructure-for-decentralized-ai”
  src/content/blog/filecoin-as-the-infrastructure-for-decentralized-ai.md
Labels: decap-cms/draft

#842 Create Blog Post “announcing-the-filecoin-nv24-tuk-tuk-upgrade-enhancing-filecoin-s-efficiency”
  public/assets/images/blog-post-header-nv24-upgrade.webp
  src/content/blog/announcing-the-filecoin-nv24-tuk-tuk-upgrade-enhancing-filecoin-s-efficiency.md
Labels: decap-cms/pending_publish

#841 Create Event “the-filecoin-penthouse-davos-2024”
  src/content/events/the-filecoin-penthouse-davos-2024.md
Labels: decap-cms/pending_publish

#859 Update Event “the-filecoin-penthouse-davos-2025”
  public/assets/images/davos-penthouse-25.webp
  src/content/events/the-filecoin-penthouse-davos-2025.md
Labels: decap-cms/pending_publish

#861 Create Event “filecoin-orbit-kampala-fvm-hack-day”
  public/assets/images/orbit-placeholder.webp
  src/content/events/filecoin-orbit-kampala-fvm-hack-day.md
Labels: decap-cms/pending_publish

#862 Create Event “filecoin-orbit-playground-16-ai-and-data-storage-for-workforce”
  src/content/events/filecoin-orbit-playground-16-ai-and-data-storage-for-workforce.md
Labels: decap-cms/pending_publish

#863 Create Event “vision-weekend”
  src/content/events/vision-weekend-usa-2024.md
Labels: decap-cms/pending_publish
