Repository FilecoinFoundationWeb/filecoin-foundation, pull requests merged in 2025-09, with the labels that each got.

#1752 Create Ecosystem Project “filswan”
  apps/ff-site/public/assets/images/swan_logo_01.1ce0d52.webp
  apps/ff-site/src/content/ecosystem-explorer/filswan.md
Labels: decap-cms/pending_publish

#1740 [SHARED][UXIT-3218] Add label-based workflows for pull requests [skip percy]
  .github/workflows/label-pr-workflow.yml
Labels: size/M

#1753 Create Ecosystem Project “gelato”
  apps/ff-site/src/content/ecosystem-explorer/gelato.md
Labels: decap-cms/pending_publish

#1757 [FILECOIN V3][UXIT-3220] Use SVGs for logos [skip percy]
  apps/filecoin-site/public/assets/miniatures/akave-miniature.png
  apps/filecoin-site/public/assets/miniatures/akave-miniature.svg
  apps/filecoin-site/public/assets/miniatures/cid-gravity-miniature.png
  apps/filecoin-site/public/assets/miniatures/cid-gravity-miniature.svg
  apps/filecoin-site/public/assets/miniatures/lighthouse-miniature.png
  apps/filecoin-site/public/assets/miniatures/lighthouse-miniature.svg
  apps/filecoin-site/public/assets/miniatures/ramo-miniature.png
  apps/filecoin-site/public/assets/miniatures/ramo-miniature.svg
  apps/filecoin-site/public/assets/miniatures/singularity-miniature.png
  apps/filecoin-site/public/assets/miniatures/singularity-miniature.svg
  apps/filecoin-site/public/assets/miniatures/storacha-miniature.png
  apps/filecoin-site/public/assets/miniatures/storacha-miniature.svg
  apps/filecoin-site/src/app/store-data/components/StorageProviderCard/StorageProviderCard.tsx
  apps/filecoin-site/src/app/store-data/data/storageProviders.ts
Labels: size/L

#1762 Update Event “virtual-fil-dev-summit-7”
  apps/ff-site/src/content/events/virtual-fil-dev-summit-7.md
Labels: decap-cms/pending_publish, size/M

#1758 [FF] New Ecosystem Project: cdid-protocol-creative-decentralized-identity
  apps/ff-site/public/assets/images/cdid-protocol-logo.png
  apps/ff-site/src/content/ecosystem-explorer/cdid-protocol.md
Labels: size/S

#1767 [FILECOIN][UXIT-3234] Add TinaCMS config file [skip percy]
  apps/filecoin-site/package.json
  apps/filecoin-site/tina/.gitignore
  apps/filecoin-site/tina/config.ts
  apps/filecoin-site/tina/schema/blog.ts
  apps/filecoin-site/turbo.json
  package-lock.json
Labels: size/L

#1768 [SHARED][UXIT-3278] Fix outputFileTracingRoot error [skip percy]
  packages/next-config/src/tracing.js
Labels: size/S

#1774 [FILECOIN][UXIT-3292] Update image on /community-hub [skip percy]
  apps/filecoin-site/public/assets/graphics/earth-at-night.png
  apps/filecoin-site/public/assets/graphics/earth-at-night.webp
  apps/filecoin-site/public/assets/graphics/earth-blue-edge.webp
  apps/filecoin-site/src/app/_data/graphicsData.ts
  apps/filecoin-site/src/app/community-hub/page.tsx
  apps/filecoin-site/src/app/learn/page.tsx
Labels: size/M

#1760 [FF][UXIT-3235] Remove broken links [skip percy]
  apps/ff-site/src/content/blog/developer-grants-updates-august-2024.md
  apps/ff-site/src/content/blog/empowering-governance-the-launch-of-metropolis-to-the-filecoin-community.md
  apps/ff-site/src/content/blog/filecoin-foundation-2024-annual-report.md
  apps/ff-site/src/content/blog/fresh-from-ff-early-july-2024.md
  apps/ff-site/src/content/blog/fresh-from-ff-early-september-2024.md
  apps/ff-site/src/content/blog/fresh-from-ff-february-2025.md
  apps/ff-site/src/content/blog/fresh-from-ff-mid-june-2024.md
  apps/ff-site/src/content/blog/fresh-from-ff-september-2025.md
  apps/ff-site/src/content/ecosystem-explorer/flare-api-portal.md
  apps/ff-site/src/content/events/davos.md
  apps/ff-site/src/content/events/vision-weekend-2022.md
Labels: size/L

#1770 [FF][UXIT-2730] Allocators Page · Update schema
  apps/ff-site/src/app/filecoin-plus/allocators/components/AllocatorsTable.tsx
  apps/ff-site/src/app/filecoin-plus/allocators/components/AllocatorsTableFilters.tsx
  apps/ff-site/src/app/filecoin-plus/allocators/components/AllocatorsTableWithFilters.tsx
  apps/ff-site/src/app/filecoin-plus/allocators/components/SearchFilter.tsx
  apps/ff-site/src/app/filecoin-plus/allocators/components/SelectFilter.tsx
  apps/ff-site/src/app/filecoin-plus/allocators/components/SelectSort.tsx
  apps/ff-site/src/app/filecoin-plus/allocators/data/allocatorsTableColumnsData.tsx
  apps/ff-site/src/app/filecoin-plus/allocators/schemas/AllocatorFileSchema.ts
  apps/ff-site/src/app/filecoin-plus/allocators/schemas/AllocatorSchema.ts
  apps/ff-site/src/app/filecoin-plus/allocators/schemas/AllocatorWithDatacapSchema.ts
  apps/ff-site/src/app/filecoin-plus/allocators/schemas/AllocatorsSchema.ts
  apps/ff-site/src/app/filecoin-plus/allocators/schemas/DatacapSchema.ts
  apps/ff-site/src/app/filecoin-plus/allocators/utils/extractAllocators.ts
  apps/ff-site/src/app/filecoin-plus/allocators/utils/generateSortedOptions.ts
  apps/ff-site/src/app/filecoin-plus/allocators/utils/getAllocatorUrlList.ts
  apps/ff-site/src/app/filecoin-plus/allocators/utils/getAllocators.ts
  apps/ff-site/src/app/filecoin-plus/allocators/utils/getColumnOrThrow.ts
Labels: size/L

#1780 [SHARED][UXIT-3312] Improve Dependabot PR titles for npm and Actions updates [skip percy]
  .github/dependabot.yml
Labels: size/S

#1795 [DECAP CMS][FF] Update Event 'virtual-fil-dev-summit-7'
  apps/ff-site/src/content/events/virtual-fil-dev-summit-7.md
Labels: decap-cms/pending_publish, size/S

#1796 [DECAP CMS][FF] Update Event 'virtual-fil-dev-summit-7'
  apps/ff-site/public/assets/images/devsummit7_virtual_main.png
  apps/ff-site/src/content/events/virtual-fil-dev-summit-7.md
Labels: decap-cms/pending_publish, size/M

#1786 [FF][UXIT-3271] Configure Airtable client timeout and retry logic
  apps/ff-site/src/app/orbit/schema/AirtableRecordSchema.ts
  apps/ff-site/src/app/orbit/services/airtable.ts
  apps/ff-site/turbo.json
Labels: size/S

#1797 [SHARED][UXIT-3198] Move ignoredClientErrors from edge to client
  apps/ff-site/instrumentation-client.ts
  apps/ff-site/sentry.edge.config.ts
  apps/ff-site/src/content/events/virtual-fil-dev-summit-7.md
  apps/ffdweb-site/instrumentation-client.ts
  apps/ffdweb-site/sentry.edge.config.ts
  apps/filecoin-site/instrumentation-client.ts
  apps/filecoin-site/sentry.edge.config.ts
  packages/sentry-config/src/ignoredErrors.ts
Labels: size/M

#1802 [FILECOIN][UXIT-3327] Fix blog test path to include locale directory
  apps/filecoin-site/cypress/e2e/blog_slug.cy.ts
Labels: size/S

#1805 [FILECOIN] Store Data Page · Redesign
  apps/filecoin-site/src/app/_components/Badge.tsx
  apps/filecoin-site/src/app/learn/data/filecoinFeatures.ts
  apps/filecoin-site/src/app/learn/page.tsx
  apps/filecoin-site/src/app/store-data/components/StorageProviderCard/StorageProviderCard.tsx
  apps/filecoin-site/src/app/store-data/data/storageProviders.ts
  apps/filecoin-site/src/app/store-data/page.tsx
Labels: size/M

#1808 [FILECOIN] Case Studies page · Remove CTA [skip percy]
  apps/filecoin-site/src/app/case-studies/page.tsx
Labels: size/S
